name: Publish NPM Package
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Prepare git to allow yarn to git commit when making version
      run: git config user.email "git@git.com" && git config user.name "github actions"
    - name: Set version
      run: yarn version --new-version `echo ${{ github.event.release.tag_name }}` --git-tag-version=false
    - run: yarn install
    - run: yarn prepare
    - name: Publish
      run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc && yarn publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_PACIFA_REGISTRY_TOKEN}}
